import os
from PIL import Image, ImageDraw, ImageFont, ImageOps

# Source files generated by AI
BRAIN_DIR = r"C:\Users\user\.gemini\antigravity\brain\9d9605af-a205-47db-937a-04dc434d6e05"
GOLD_BASE = os.path.join(BRAIN_DIR, "gold_badge_1772153635176.png")
DIAMOND_BASE = os.path.join(BRAIN_DIR, "diamond_badge_1772153780763.png")
SILVER_BASE = os.path.join(BRAIN_DIR, "silver_badge_1772153795567.png")
BLUE_MEDAL = os.path.join(BRAIN_DIR, "punctual_medal_1772154937459.png")
SCHOOL_LOGO = os.path.join(BRAIN_DIR, "school_logo_1772154287328.png")

os.makedirs("assets/badges", exist_ok=True)
os.makedirs("assets/images", exist_ok=True)

def make_transparent_and_resize(img_path, size=(250, 250)):
    if not os.path.exists(img_path):
        return None
    img = Image.open(img_path).convert("RGBA")
    data = img.getdata()
    new_data = []
    # Make near-white pixels transparent
    for item in data:
        if item[0] > 235 and item[1] > 235 and item[2] > 235:
            new_data.append((255, 255, 255, 0))
        else:
            new_data.append(item)
    img.putdata(new_data)
    img = img.resize(size, Image.Resampling.LANCZOS)
    return img

def add_text_to_badge(badge_img, text1, text2, output_path):
    if badge_img is None:
        return
    img = badge_img.copy()
    draw = ImageDraw.Draw(img)
    try:
        font1 = ImageFont.truetype("arialbd.ttf", 36)
        font2 = ImageFont.truetype("arial.ttf", 24)
    except:
        font1 = ImageFont.load_default()
        font2 = ImageFont.load_default()
        
    width, height = img.size
    
    # Calculate text widths
    bbox1 = draw.textbbox((0, 0), text1, font=font1)
    bbox2 = draw.textbbox((0, 0), text2, font=font2)
    w1, w2 = bbox1[2] - bbox1[0], bbox2[2] - bbox2[0]
    
    # Draw centered text with a very strong shadow/outline for contrast
    y_center = height // 2
    
    # Text 1 (Subject name) - Make it bright white with strong black stroke/shadow
    draw.text(((width - w1)/2 + 2, y_center - 25 + 2), text1, font=font1, fill="black")
    draw.text(((width - w1)/2 - 1, y_center - 25 - 1), text1, font=font1, fill="black")
    draw.text(((width - w1)/2 + 1, y_center - 25 - 1), text1, font=font1, fill="black")
    draw.text(((width - w1)/2 - 1, y_center - 25 + 1), text1, font=font1, fill="black")
    draw.text(((width - w1)/2, y_center - 25), text1, font=font1, fill="white")
    
    # Text 2 (Tier text) - Make it pop based on contrast
    draw.text(((width - w2)/2 + 1, y_center + 15 + 1), text2, font=font2, fill="black")
    draw.text(((width - w2)/2, y_center + 15), text2, font=font2, fill="#FFD700") # Bright goldish yellow
    
    img.save(output_path)

# Prepare bases
gold_img = make_transparent_and_resize(GOLD_BASE)
diamond_img = make_transparent_and_resize(DIAMOND_BASE)
silver_img = make_transparent_and_resize(SILVER_BASE)

subjects = ["Urdu", "English", "Maths", "Biology", "Computer", "Chemistry", "Physics", "Islamiat", "Pak Studies"]

print("Composing Subject Badges...")
for sub in subjects:
    add_text_to_badge(gold_img, sub, "Genius", f"assets/badges/{sub}_Genius.png")
    add_text_to_badge(diamond_img, sub, "Expert", f"assets/badges/{sub}_Expert.png")
    add_text_to_badge(silver_img, sub, "Star", f"assets/badges/{sub}_Star.png")

print("Composing Trait Badges...")
blue_base = make_transparent_and_resize(BLUE_MEDAL)
add_text_to_badge(blue_base, "Punctual", "Student", "assets/badges/punctual.png")

if blue_base:
    # Colorize blue medal to green for obedient
    gray = ImageOps.grayscale(blue_base.convert("RGB"))
    green_tint = ImageOps.colorize(gray, black="black", white="lightgreen", mid="darkgreen")
    # Put transparency back
    green_tint = green_tint.convert("RGBA")
    r,g,b,a = blue_base.split()
    green_tint.putalpha(a)
    add_text_to_badge(green_tint, "Obedient", "Student", "assets/badges/obedient.png")

print("Saving Logo...")
logo_img = make_transparent_and_resize(SCHOOL_LOGO, size=(120, 120))
if logo_img:
    logo_img.save("assets/images/school_logo.png")

print("Badges Composited Successfully!")
